### ISSUE TITLE
Agency vs Agencies

### ISSUE THREAD

**Issue by khr15714n** [steedcrugeon/PicoPort#2]
[ERR             ] [Agent]: Cannot find logo at url 'SHED/Agency/SHEDLogoC'
[ERR             ] [Agent]: Cannot find logo scaled at url 'SHED/Agency/SHEDLogoC_SM'

SHED/Agencies/SHEDAgency.cfg

    logoURL = SHED/Agency/SHEDLogoC
    logoScaledURL = SHED/Agency/SHEDLogoC_SM

Either /Agency/ or /Agencies/

**Comment by steedcrugeon** [comment]
This has been resolved in v0.1.3
